name: servio
description: "Servio - On-Demand Home Services Booking Flutter Application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  # UI, Layout & Typography
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  animated_bottom_navigation_bar: ^1.3.3
  cached_network_image: ^3.4.1
  shimmer: ^4.0.0
  gap: ^3.0.1
  iconsax: ^0.0.8
  intl: ^0.20.2

  # State Management & Animations
  get: ^4.7.3
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

# Launcher Icons Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#004E42"
  adaptive_icon_foreground: "assets/app_icon.png"

# Flutter Assets Configuration
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/profile/
    - assets/certificates/
    - assets/samples/
